name: Go package

on: [push]
# TODO fix rules, deploy on merge or smtf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o app .

      - name: Test
        run: go test -v ./...

      - name: Transfer
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v3
        with:
          name: app
          path: /tmp/app

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            ls -la
            ls -la /tmp
            pwd
            scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /tmp/app ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/app