name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o app .

      - name: Test
        run: go test -v ./...

      - name: Package
        run: upx app

      - name: Transfer
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            scp app ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/app
            ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "./app"